export const CREDIT_AUDIT_CHECKLIST: ReadonlyArray<{ id: number; label: string }> = [
  { id: 1, label: "KYC compliance (KYC of Promoter/Partners/Guarantors, Opinion Report, CIBIL etc.)" },
  { id: 2, label: "Financial due diligence (Past annual/quarterly financials, sales/gross profits, AR, projections vs actual etc.)" },
  { id: 3, label: "Legal due diligence (Contracts, leases, business registration documents, sales contracts etc.)" },
  { id: 4, label: "Quality of Appraisal / Term Loan: Analysis of Balance Sheet" },
  { id: 5, label: "Quality of Appraisal / Working Capital Assessment" },
  { id: 6, label: "Quality of Appraisal / Term Loan / Project Appraisal" },
  { id: 7, label: "Valuation report of primary collateral obtained" },
  { id: 8, label: "Audited Balance Sheet submitted within 6–8 months from BS date" },
  { id: 9, label: "Statutory dues and compliance reviewed; comments recorded" },
  { id: 10, label: "End-use / verification controls as per policy; comments recorded" },
  { id: 11, label: "Borrower financial position / conduct of account reviewed" },
  { id: 12, label: "Sanction terms complied; deviations (if any) recorded" },
  { id: 13, label: "Disbursement controls followed (conditions precedent / margin etc.)" },
  { id: 14, label: "Ratio analysis comment (CR, DER, GP Ratio, NP Ratio, TOL/TNW, DSCR)" },
  { id: 15, label: "Submission of stock statement – comment" },
  { id: 16, label: "Appropriate sanctions recorded in all cases" },
  { id: 17, label: "Delegation of powers adhered in all sanctions" },
  { id: 18, label: "Administrative clearances obtained wherever necessary" },
  { id: 19, label: "Control returns submitted and sanctions/approvals taken on record / noted by authority" },
  { id: 20, label: "Opinion reports on borrowers/guarantors and financial status of associate companies compiled & updated" },
  { id: 21, label: "Arrangement letter conveying all sanction terms acknowledged by borrower & guarantor; kept on record (including renewals)" },
  { id: 22, label: "Security documents are enforceable and complete" },
  { id: 23, label: "Documents execution completed properly (stamp, sign, witness, dates etc.)" },
  { id: 24, label: "Insurance policies obtained; bank clause/charge noted; renewals monitored" },
  { id: 25, label: "Primary/collateral charge creation process completed as applicable" },
  { id: 26, label: "Proper documentation for hypothecation / pledge / mortgage maintained" },
  { id: 27, label: "Periodic review/renewal of limits carried out as per policy" },
  { id: 28, label: "Stock/book-debts verification done; DP calculated correctly and updated" },
  { id: 29, label: "Unit/stock inspection carried out as per periodicity; reports available" },
  { id: 30, label: "IRAC classification correctly done as per RBI guidelines for latest quarter" },
  { id: 31, label: "Loan processing charge / upfront fee etc. recovered as per sanction / instructions" },
  { id: 32, label: "Interest rate correctly applied on all loan accounts" },
  { id: 33, label: "Account operations/transactions monitored; irregularities, if any, recorded" },
  { id: 34, label: "Covenants monitoring: submission of statements/returns as per sanction" },
  { id: 35, label: "Compliance with RBI / Bank guidelines relevant to facility and borrower" },
  { id: 36, label: "Title deeds / charge documents kept safely; custody controls followed" },
  { id: 37, label: "EM Register / Title Deeds Register properly maintained" },
  { id: 38, label: "Registration of EM (CERSAI, recital, confirmation of EM, noting of bank’s charge with revenue authority, NEC etc.)" },
  { id: 39, label: "Second charge / pari-passu charge created properly wherever applicable" },
  { id: 40, label: "Problem loan handling / recovery actions (if applicable) reviewed and recorded" },
  { id: 41, label: "Any other action proposed / observations" },
] as const;